<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6JUGJ4I" failures="4" tests="28" name="tests.RegisterPageTest" time="202.241" errors="0" timestamp="2022-12-21T16:06:42 IST" skipped="2">
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldDesiredPassword" time="6.560"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldPhoneNumber" time="8.531"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldPhoneNumber" time="6.999"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingblankEmail" time="9.566"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingblankUserName" time="8.388"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldFullName" time="7.601"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldEmailId" time="8.418"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="withoutAcceptingTerms" time="6.952"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingBlankPhoneNumber" time="7.112"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingblankEmail" time="7.340"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingValidRegistrationData" time="7.044">
    <failure message="expected [https://accounts.lambdatest.com/email/verify] but found [https://accounts.lambdatest.com/register]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://accounts.lambdatest.com/email/verify] but found [https://accounts.lambdatest.com/register]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at tests.RegisterPageTest.providingValidRegistrationData(RegisterPageTest.java:219)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- providingValidRegistrationData -->
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldTermsAndPrivacyPolicy" time="9.629"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldFullName" time="9.718"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldTermsAndPrivacyPolicy" time="6.836"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingValidRegistrationData" time="7.909">
    <failure message="expected [https://accounts.lambdatest.com/email/verify] but found [https://accounts.lambdatest.com/register]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://accounts.lambdatest.com/email/verify] but found [https://accounts.lambdatest.com/register]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at tests.RegisterPageTest.providingValidRegistrationData(RegisterPageTest.java:219)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- providingValidRegistrationData -->
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingShortPassword" time="5.389"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldCompnyName" time="5.192">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.RegisterPageTest.testFunctionalFieldCompnyName(RegisterPageTest.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testFunctionalFieldCompnyName -->
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldDesiredPassword" time="8.508"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingShortPassword" time="7.356"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldFreeSignUp" time="8.319"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldFreeSignUp" time="7.083"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldEmailId" time="8.474"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingBlankPhoneNumber" time="6.436"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingblankUserName" time="11.648"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="testFunctionalFieldCompnyName" time="7.518">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.RegisterPageTest.testFunctionalFieldCompnyName(RegisterPageTest.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- testFunctionalFieldCompnyName -->
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="withoutAcceptingTerms" time="7.715"/>
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingRegisteredEmail">
    <skipped/>
  </testcase> <!-- providingRegisteredEmail -->
  <system-out/>
  <testcase classname="tests.RegisterPageTest" name="providingRegisteredEmail">
    <skipped/>
  </testcase> <!-- providingRegisteredEmail -->
  <system-out/>
</testsuite> <!-- tests.RegisterPageTest -->
